### ISSUE TITLE
Should have a set of used template params for every item id

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/octh#11]
When I make too many items opaque, I get the error `Should have a set of used template params for every item id`. I got this error on the `opaque` branch when I tried making `std::basic_streambuf` opaque.

**Comment by ctaggart** [comment]
Using the latest on bindgen master fixes this. To get the latest on master, edit cargo.toml and then `cargo update`.
``` toml
[build-dependencies]
# bindgen = "*"
bindgen = { git = "https://github.com/servo/rust-bindgen" }
```
